### ISSUE TITLE
Culling

### ISSUE THREAD

**Issue by mrocklin** [mrocklin/dask-expr#12]
There has been pain around graph culling in the past.  We want to be efficient in cases where people ask for only a small subset of the output result, and that requires only a small subset of the graph to be generated.  This occurs in situations like `.head` and array slicing.  

My _hope_ is that a lot of this pain goes away with high level optimization.  For example we should have optimizations that push `.head` through many operations (everything except IO, shuffling, ACA, etc..).  Even then there are a couple of options:

1.  Have operations like read_parquet and shuffle know the output partitions that are requested as part of their own metadata (so the head operation disappears entirely once optimized)
2. Keep the head optimization around, and accept some wasted generation, but feel glad because it's only happening on one layer, rather than on many layers.

Regardless, a good first step here, I think, is to build some optimizations around Head

**Comment by rjzamora** [comment]
Related: https://github.com/mrocklin/dask-match/pull/16

**Comment by rjzamora** [comment]
Now that we have `Partitions` and `PartitionsFiltered`, I think we have a reasonable plan to handle culling. Therefore, I'm going to close this issue.

If we run into culling-related pain in the future, we can reference this issue in a separate discussion.
